[package]
name = "pket"
pack = "badgardener.pket"
version = "26.1.3"
description = "A simple application packager, installer and manager."
authors = ["badgardener"]

[files]
base = "dist"
assets = ["../LICENSE", "../README.md"] # Goes inside @res/pket-assets/*

[[executable]]
path = "bin/pket-linux-example.sh"
link = "pket"

# [install]
# preinstall = "@res/bin/pket.exe --version"
# postinstall = "pket --version"
