[package]
name = "pket-example"
pack = "badgardener.pket.example"
version = "1.0.0"
description = "A simple application packager, installer and manager (example)."
authors = ["badgardener"]

[files]
base = "dist"
assets = ["../LICENSE", "../README.md"] # Goes inside @res/pket-assets/*

[[executable]]
path = "bin/pket-linux-example.sh"
link = "pket"

[install]
# preinstall = "@res/bin/pket.exe --version"
postinstall = "pket --version"
